repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Format code
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/myint/autoflake.git
    rev: v2.1.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--force-single-line-imports]
  - repo: https://github.com/myint/docformatter.git
    rev: v1.7.2
    hooks:
      - id: docformatter
        args:
          [
            "--in-place",
            "--wrap-summaries=80",
            "--wrap-descriptions=80",
            "--pre-summary-newline",
          ]
  - repo: https://github.com/ikamensh/flynt/
    rev: '0.78'
    hooks:
      - id: flynt
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
    -   id: python-use-type-annotations
    -   id: python-no-eval
    -   id: python-no-log-warn
